### ISSUE TITLE
Broken desktop form preview

### ISSUE THREAD

**Issue by nastassia-schulz** [sw-code/sw-code.github.io#10]
exabple is in pp portal -> PP_DEMO_USER -> Anamnesebogen -> Medikamente tab
![Image](https://github.com/sw-code/sw-code.github.io/assets/49995123/5a81919d-6f92-4abc-8836-272f038a6c53)

**Comment by viktorgt** [comment]
wrong repo?

**Comment by johannesvollmer** [comment]
yes :)
